config:
  guestbook_name: "Wenlin PopRock Festival 2.0"
  backend_uri: "backend.minikube.local/guestbook"
replicaCount: 1
image:
  repository: jackhwl/frontend
  tag: "2.0"
service:
  port: 80
  type: ClusterIP
ingress:
  enabled: true
  host: frontend.minikube.local